"""
LongBench Real Context Stress Test (Distributed Architecture Grid)
==================================================================
Goal: Test the "Dispatching & Aggregation Logic" of the parallel writer architecture.
      Not testing context limit, but coherence and redundancy.

Data: Real MultiNews dataset (HuggingFace, pre-downloaded by fetch_real_data.py).
Simulation: Inject multi-source news documents (8k-180k tokens) directly into the agent's
            context, bypassing the search step to focus on planning and writing.

Scoring:
  - Coherence Score (Llama 3 Judge): Are transitions between sections smooth?
  - Redundancy Score (Llama 3 Judge): Is information repeated across sections?
  - Insight Score (Llama 3 Judge): Does the final report synthesize global insights?
"""
import pytest
import sys
import os
import json

# Fix Windows encoding
if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

# Ensure project root is on path
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, PROJECT_ROOT)

from tests.adapter import invoke_agent_with_custom_context

# --------------------------------------------------------------------------
#  Data Loading (from pre-generated cache)
# --------------------------------------------------------------------------
LONGBENCH_CACHE = os.path.join(PROJECT_ROOT, "data", "longbench_subset.json")

def get_longbench_data():
    """Load cached MultiNews subset (generated by fetch_real_data.py)."""
    if os.path.exists(LONGBENCH_CACHE):
        with open(LONGBENCH_CACHE, "r", encoding="utf-8") as f:
            return json.load(f)

    pytest.fail(
        f"数据文件不存在: {LONGBENCH_CACHE}\n"
        f"请先运行: F:\\Conda_Envs\\agent_env\\python.exe fetch_real_data.py"
    )
    return []

# --------------------------------------------------------------------------
#  Judge Prompts
# --------------------------------------------------------------------------
def evaluate_coherence_redundancy(judge, report: str) -> dict:
    """Evaluate coherence and redundancy using the Judge."""
    prompt = f"""You are an expert editor evaluating a research report generated by a parallel-writer AI system.

REPORT CONTENT:
{report[:15000]}... (truncated)

Critique this report on two specific dimensions:

1. COHERENCE (1-10): Do the sections flow logically? Are there abrupt transitions or disjointed styles?
2. REDUNDANCY (1-10): Is the same specific information repeated in multiple sections? (10 = no redundancy, clean; 1 = high redundancy).

Output Format:
COHERENCE SCORE: X/10
REDUNDANCY SCORE: Y/10
REASONING: [Brief explanation]
"""
    response = judge.generate(prompt)
    return {"raw_response": response}

# --------------------------------------------------------------------------
#  Test Case
# --------------------------------------------------------------------------
REPORT_OUTPUT_PATH = os.path.join(PROJECT_ROOT, "tests", "stress_test_report.md")

def _save_report(report: str, task_id: str, eval_text: str = ""):
    """Append stress test result to a persistent report file."""
    with open(REPORT_OUTPUT_PATH, "a", encoding="utf-8") as f:
        f.write(f"\n## LongBench Stress Test: {task_id}\n")
        f.write(f"- Report Length: {len(report)} chars\n")
        if eval_text:
            f.write(f"- Judge Evaluation:\n```\n{eval_text}\n```\n")
        f.write(f"\n<details><summary>Full Report (click to expand)</summary>\n\n")
        f.write(report[:5000])  # Truncated for readability
        f.write(f"\n\n...(truncated, total {len(report)} chars)\n</details>\n\n---\n")

@pytest.mark.longbench
@pytest.mark.parametrize(
    "task",
    get_longbench_data(),
    ids=lambda t: t.get("id", "unknown")
)
def test_distributed_stress_test(task, judge_llm):
    """
    Run the agent with INJECTED context (10k+ tokens) to stress test
    the planner's decomposition and writer's de-duplication logic.
    """
    input_docs = task["input_docs"]
    
    print(f"\n{'='*65}")
    print(f"  LongBench Stress Test | Task: {task.get('id', 'unknown')}")
    print(f"  Length: {task['length']} tokens")
    print(f"  Source: MultiNews (real news clusters)")
    print(f"{'='*65}")
    
    query = "Summarize the key events and conflicting perspectives in these news reports. Ensure a unified narrative."
    
    # Run Agent with FORCED CONTEXT
    print(f"  Injecting {len(input_docs)} chars of context...")
    result = invoke_agent_with_custom_context(query, context_str=input_docs)
    
    report = result["actual_output"]
    print(f"  Generated Report Length: {len(report)} chars")
    
    # Core assertion: Agent must produce something substantial
    assert len(report) > 500, "Report generated is too short!"
    
    # Evaluate with Judge (graceful fallback if Ollama unavailable)
    eval_text = ""
    try:
        eval_res = evaluate_coherence_redundancy(judge_llm, report)
        eval_text = eval_res['raw_response']
        print(f"  [Evaluation]\n{eval_text}")
    except Exception as e:
        eval_text = f"Judge unavailable: {e}"
        print(f"  ⚠️  [Judge Skipped] Ollama not available: {e}")
        print(f"  ℹ️  Report saved for manual review.")
    
    # Save report for manual review
    _save_report(report, task.get("id", "unknown"), eval_text)
    print(f"  ✅ Report saved to {REPORT_OUTPUT_PATH}")


