import json
import os
from datetime import datetime
from typing import List, Dict, Optional

class TrainingDataRecorder:
    def __init__(self, filename="data/sft_training_data.jsonl"):
        self.filename = filename
        # Ensure directory exists
        os.makedirs(os.path.dirname(filename), exist_ok=True)

    def save_trajectory(self, 
                       task_id: str, 
                       query: str, 
                       history: List[Dict], 
                       final_report: str, 
                       score: Optional[float] = None):
        """
        Saves high-quality execution trajectories for SFT.
        
        Args:
            task_id: Unique identifier for the task
            query: User's research query
            history: List of interaction steps (thoughts, tool calls, results)
                     Expected format: [{"role": "thought"|"tool"|"assistant", "content": "..."}]
            final_report: The final output generated by the agent
            score: Optional quality score (0-10 or 0-1)
        """
        # Filter low-quality runs (strict filtering for SFT)
        if score is not None and score < 7.0: 
            print(f"⚠️ Task {task_id} score too low ({score} < 7.0), skipping SFT data save.")
            return

        conversation = []
        
        # 1. System Prompt
        conversation.append({
            "role": "system",
            "content": "You are a Deep Research Agent capable of planning, searching, and synthesizing complex information."
        })
        
        # 2. User Instruction
        conversation.append({
            "role": "user",
            "content": f"Please conduct deep research on: {query}"
        })
        
        # 3. Reconstruct Agent's Chain of Thought & Actions from History
        for step in history:
            role = step.get("role", "assistant") 
            content = step.get("content", "")
            
            if role == "planner_cot":
                # [Llama-3 Optimization] Use <|begin_of_thought|> tags and natural language wrapper
                if isinstance(content, dict):
                    thought_str = json.dumps(content, ensure_ascii=False, indent=2)
                else:
                    thought_str = str(content)
                
                conversation.append({
                    "role": "assistant", # Llama-3 uses assistant role for thoughts usually, or specific if supported
                    "content": f"<|begin_of_thought|>\nHere is the research plan breakdown:\n1. I will analyze the user request and context.\n2. I will identify key information gaps.\n3. I will formulate specific search tasks to fill those gaps.\n\nPlan:\n{thought_str}\n<|end_of_thought|>"
                })
                
            elif role == "query_gen":
                # [Llama-3 Optimization] More descriptive and reasoning-based generation
                task_desc = content.get('task_desc')
                queries = content.get('generated_queries')
                conversation.append({
                    "role": "assistant", 
                    "content": f"To find detailed information about '{task_desc}', specifically looking for factual data and primary sources, I will use these generated queries:\n{json.dumps(queries, ensure_ascii=False)}"
                })
                
            elif role == "search_tool":
                # The actual tool execution result (Observation)
                conversation.append({
                    "role": "tool",
                    "content": f"Search Results: {str(content)[:1000]}..." 
                })
            
            elif role == "search_error":
                # Reflection
                conversation.append({
                    "role": "assistant",
                    "content": f"<|begin_of_thought|>\nSearch failed for '{content.get('query')}'. Error: {content.get('error')}. I need to adjust my keywords or try a different source.\n<|end_of_thought|>"
                })

        # 4. Final Report
        conversation.append({
            "role": "assistant",
            "content": final_report
        })

        # Construct Training Sample
        training_sample = {
            "id": f"deep_research_{task_id}",
            "timestamp": datetime.now().isoformat(),
            "score": score,
            "messages": conversation
        }

        # Append to file
        try:
            with open(self.filename, "a", encoding="utf-8") as f:
                f.write(json.dumps(training_sample, ensure_ascii=False) + "\n")
            print(f"💾 [SFT Data] Successfully saved trajectory for task {task_id}!")
        except Exception as e:
            print(f"❌ Failed to save SFT data: {e}")
